[phases.setup]
nixPkgs = [
  "gcc",
  "libffi",
  "openssl",
  "zlib",
  "libpq",
  "python310Full"
]

[phases.install]
cacheDirectories = ["/opt/venv"]
# Combine all commands in one install section
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app -b 0.0.0.0:$PORT"