services:
  - type: web
    name: stock management system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legitdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true